# Generated by Django 4.0.4 on 2022-06-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_and_brand', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
