# Generated by Django 4.0.4 on 2022-06-13 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_and_brand', '0002_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
