# Generated by Django 4.0.4 on 2022-06-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_and_brand', '0003_alter_plan_plan_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoals',
            name='benefit_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='benefit_type',
            field=models.CharField(blank=True, choices=[('CB', 'Cashback'), ('EV', 'Extra Voucher')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='deposited_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='selected_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='selected_tenure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='started_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
