# Generated by Django 4.0.4 on 2022-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_and_brand', '0004_alter_customergoals_benefit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandpromotion',
            name='users',
            field=models.IntegerField(default=0, verbose_name='For how many users this promotion will be valid'),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='benefit_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='deposited_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='selected_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customergoals',
            name='selected_tenure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
